//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_RandomNumber.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RandomNumberEntities : DbContext
    {
        public RandomNumberEntities()
            : base("name=RandomNumberEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tbl_ActionType> Tbl_ActionType { get; set; }
        public virtual DbSet<Tbl_Player> Tbl_Player { get; set; }
        public virtual DbSet<Tbl_PlayerType> Tbl_PlayerType { get; set; }
        public virtual DbSet<Tbl_Syntax> Tbl_Syntax { get; set; }
        public virtual DbSet<Tbl_CashOut> Tbl_CashOut { get; set; }
    }
}
