//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_RandomNumber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CashOut
    {
        public int Id { get; set; }
        public Nullable<System.Guid> guid { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public Nullable<int> ActionTypeId { get; set; }
        public Nullable<double> Ratio { get; set; }
        public string Description { get; set; }
    }
}
