//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_RandomNumber.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ActionType
    {
        public int Id { get; set; }
        public System.Guid guid { get; set; }
        public string Name { get; set; }
        public Nullable<int> ActionTypeLevel { get; set; }
        public Nullable<int> InCoin { get; set; }
        public Nullable<int> OutCoin { get; set; }
        public Nullable<bool> IsFirstChirld { get; set; }
        public string Description { get; set; }
    }
}
